pygments: true
auto: true
permalink: none
hashtag: '#btvwag'
twitter_search: 'btvwag'
github_login: 'btvwag'
github_repo: 'btvwag.github.com'
github_language: ['Javascript', 'Ruby', 'PHP', 'Python']
email: info@agilionapps.com
